#!/bin/sh

set -e

case "$1" in
    purge)
	rm -rf /var/spool/opensmtpd
        for name in opensmtpd opensmtpq; do
            # By debian Policy §6.5, we may only rely on essential packages and
            # must fail gracefully if they are unavailable.
            # Use userdel/groupdel from passwd instead of deluser/delgroup from
            # the adduser package. This is because adduser depends on passwd,
            # but is of lesser priority.
            # Note that at the time of this writing, neither passwd nor adduser
            # are essential packages.
            userdel  ${name} >/dev/null 2>&1 || true;
            groupdel ${name} >/dev/null 2>&1 || true;
        done
	;;

    remove|failed-upgrade|abort-install|abort-upgrade|disappear|upgrade)
	;;

    *)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d opensmtpd remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

