#!/bin/sh
# postinst script for opensmtpd
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
        update-rc.d opensmtpd defaults
        service opensmtpd start
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
