#!/bin/sh
# prerm script for opensmtpd

set -e

case "$1" in
    remove)
        service opensmtpd stop
    ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade|deconfigure)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
